package com.example.tema1;

public class HeroData {

    private Hero [] heroes= {
            new Hero("Ant-Man",         " Scott Edward Harris Lang ", "Paul Rudd", "ability to shrink to sub-microscopic size and enter the subatomic universes, genius-level intellect, size-shifting from nearly microscopic to ~100 feet gigantic, ability to transfer his size-shifting ability to other beings and objects", "Forced out of his own company by former protégé Darren Cross, Dr. Hank Pym (Michael Douglas) recruits the talents of Scott Lang (Paul Rudd), a master thief just released from prison. Lang becomes Ant-Man, trained by Pym and armed with a suit that allows him to shrink in size, possess superhuman strength and control an army of ants. The miniature hero must use his new skills to prevent Cross, also known as Yellowjacket, from perfecting the same technology and using it as a weapon for evil", "antman.jpg", "antmanlogo.jpg", "https://marvelcinematicuniverse.fandom.com/wiki/Ant-Man"),
            new Hero("Aquaman",         "       Arthur Curry       ", "Jason Momoa", "superhuman strength, intelliegence, durability, endurance, speed, agility, and senses, telepathic control of all aquatic life, utilizing the Sacred Trident, proficient in magic, skilled martial artist, underwater adaption, hydrokinesis, extreme night vision", "Once home to the most advanced civilization on Earth, the city of Atlantis is now an underwater kingdom ruled by the power-hungry King Orm. With a vast army at his disposal, Orm plans to conquer the remaining oceanic people -- and then the surface world. Standing in his way is Aquaman, Orm's half-human, half-Atlantean brother and true heir to the throne. With help from royal counselor Vulko, Aquaman must retrieve the legendary Trident of Atlan and embrace his destiny as protector of the deep.","aquaman.jpg", "aquamanlogo.jpg", "https://dc.fandom.com/wiki/Aquaman_(Arthur_Curry)"),
            new Hero("Batman",          "       Bruce Wayne        ", "Christian Bale, Ben Affleck, Robert Pattinson", "genius-level intellect, expert detective, master martial artist, master tactician, strategist, and field commander, utilizes high-tech equipment and weapons", "Batman ventures into Gotham City's underworld when a sadistic killer leaves behind a trail of cryptic clues. As the evidence begins to lead closer to home and the scale of the perpetrator's plans become clear, he must forge new relationships, unmask the culprit and bring justice to the abuse of power and corruption that has long plagued the metropolis", "batman.jpg", "batmanlogo.jpg", "https://dc.fandom.com/wiki/Batman_(Bruce_Wayne)"),
            new Hero("Black Widow",     "Natalia Alianovna Romanova", "Scarlett Johansson", "Expert spy, master martial artist, slowed aging,enhanced immune system, skilled hypnotist", "Natasha Romanoff, aka Black Widow, confronts the darker parts of her ledger when a dangerous conspiracy with ties to her past arises. Pursued by a force that will stop at nothing to bring her down, Natasha must deal with her history as a spy, and the broken relationships left in her wake long before she became an Avenger.", "blackwidow.jpg", "blackwidowlogo.jpg", "https://marvelcinematicuniverse.fandom.com/wiki/Black_Widow"),
            new Hero("Captain America", "       Steven Rogers      ", "Chris Evans", "physical attributes enhanced to a super human level, expert martial artist, master tactician and field commander", "Political pressure mounts to install a system of accountability when the actions of the Avengers lead to collateral damage. The new status quo deeply divides members of the team. Captain America (Chris Evans) believes superheroes should remain free to defend humanity without government interference. Iron Man (Robert Downey Jr.) sharply disagrees and supports oversight. As the debate escalates into an all-out feud, Black Widow (Scarlett Johansson) and Hawkeye (Jeremy Renner) must pick a side.", "captain.jpg", "captainlogo.jpg", "https://marvelcinematicuniverse.fandom.com/wiki/Captain_America"),
            new Hero("Catwoman",        "        Selina Kyle       ", "Halle Berry, Anne Hathaway, Zoë Kravitz", "expert burglar, skilled martial artist and hand-to-hand combatant, skilled gymnast utilizing whips, sharp retractable claws, and climbing pitons", "\"Catwoman\" is the story of shy, sensitive artist Patience Philips (Halle Berry), a woman who can't seem to stop apologizing for her own existence. She works as a graphic designer for Hedare Beauty, a mammoth cosmetics company on the verge of releasing a revolutionary anti-aging product. When Patience inadvertently happens upon a dark secret her employer is hiding, she finds herself in the middle of a corporate conspiracy. What happens next changes Patience forever.", "catwoman.jpg", "catwomanlogo.jpg", "https://batman.fandom.com/wiki/Catwoman"),
            new Hero("Deadpool",        "   Wade Winston Wilson    ", "Ryan Reynolds", "regeneration/healing factor, skilled martial artist, master assassin, peak human speed, superhuman strength, reflexes and agility", "Wade Wilson (Ryan Reynolds) is a former Special Forces operative who now works as a mercenary. His world comes crashing down when evil scientist Ajax (Ed Skrein) tortures, disfigures and transforms him into Deadpool. The rogue experiment leaves Deadpool with accelerated healing powers and a twisted sense of humor. With help from mutant allies Colossus and Negasonic Teenage Warhead (Brianna Hildebrand), Deadpool uses his new skills to hunt down the man who nearly destroyed his life.", "deadpool.jpg", "deadpoollogo.jpg", "https://marvel.fandom.com/wiki/Deadpool"),
            new Hero("Iron Man",        "  Antonio \"Tony\" Stark  ", "Robert Downey Jr", "genius-level intellect, a powered armored suit, superhuman strength, super-sonic flight, energy blasts", "With the world now aware that he is Iron Man, billionaire inventor Tony Stark (Robert Downey Jr.) faces pressure from all sides to share his technology with the military. He is reluctant to divulge the secrets of his armored suit, fearing the information will fall into the wrong hands. With Pepper Potts (Gwyneth Paltrow) and \"Rhodey\" Rhodes (Don Cheadle) by his side, Tony must forge new alliances and confront a powerful new enemy.", "ironman.jpg", "ironmanlogo.jpg", "https://marvelcinematicuniverse.fandom.com/wiki/Iron_Man"),
            new Hero("Spider-Man",      "  Peter Benjamin Parker   ", "Tobey Maguire, Andrew Garfield, Tom Holland", "the ability to cling to solid surfaces, super-human levels of strength, speed, reflexes, prodigious skill in physics and chemistry, genius-level intellect, possesses a sixth sense, which warns him of unseen danger, along with an accelerated healing factor; utilises mechanical wrist-worn \"web-shooters\"", "\"Spider-Man\" centers on student Peter Parker (Tobey Maguire) who, after being bitten by a genetically-altered spider, gains superhuman strength and the spider-like ability to cling to any surface. He vows to use his abilities to fight crime, coming to understand the words of his beloved Uncle Ben: \"With great power comes great responsibility.\"", "spiderman.jpg", "spidermanlogo.jpg", "https://marvelcinematicuniverse.fandom.com/wiki/Spider-Man"),
            new Hero("Thor",            "        Thor Odinson      ", "Chris Hemsworth", "skilled hand to hand combatant, immense superhuman strength, stamina and durability, axe hammer grants: flight, teleportation, large scale weather manipulation, ability to control lightning", "As the son of Odin (Anthony Hopkins), king of the Norse gods, Thor (Chris Hemsworth) will soon inherit the throne of Asgard from his aging father. However, on the day that he is to be crowned, Thor reacts with brutality when the gods' enemies, the Frost Giants, enter the palace in violation of their treaty. As punishment, Odin banishes Thor to Earth. While Loki (Tom Hiddleston), Thor's brother, plots mischief in Asgard, Thor, now stripped of his powers, faces his greatest threat.", "thor.jpg", "thorlogo.jpg", "https://marvelcinematicuniverse.fandom.com/wiki/Thor"),
            new Hero("Wolverine",       "        James Howlett     ", "Hugh Jackman", "regeneration, superhuman senses, strength, reflexes, adamantium-laced skeletal structure with retractable claws, skilled martial artist", "Seeking solace from his dark past, Logan (Hugh Jackman), better known as Wolverine, seems to have found love and contentment with Kayla Silverfox (Lynn Collins). Logan's peaceful existence is shattered when Victor Creed (Liev Schreiber), his vicious brother, brutally murders Kayla. Logan's thirst for revenge propels him into the Weapon X program, where he undergoes a painful procedure to bond his bones with adamantium, making him virtually indestructible and more than a match for Victor.", "wolverine.jpg", "wolverinelogo.jpg", "https://marvel.fandom.com/wiki/James_Howlett_(Earth-616)")

    };
    public Hero [] getHeroes(){return heroes;}
    public Hero getHero(int position){return heroes[position];}
}
